spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/hwh
    username: sa
    password:
    driver-class-name: org.h2.Driver

  date:
    web:
      pageable:
        one-indexed-parameters: true

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

logging.level:
  org.hibernate.SQL: debug